### ISSUE TITLE
HelloWorld doesn't build with xtend-android-gradle-plugin:0.3.+

### ISSUE THREAD

**Issue by BAVhel** [tobykurien/Xtendroid#58]
I've tried build example HelloWorld with:
'com.android.tools.build:gradle:0.13.+'
'org.xtend:xtend-android-gradle-plugin:0.3.+'
and gradle 2.1

ERROR:  HelloWorldActivity.xtend -
15: Error during annotation processing:
java.lang.NoClassDefFoundError: android/app/Activity
        at org.xtendroid.app.AndroidActivityProcessor.doTransform(AndroidActivityProcessor.java:75)
        at org.eclipse.xtend.lib.macro.AbstractClassProcessor.doTransform(AbstractClassProcessor.java:42)
Caused by: java.lang.ClassNotFoundException: android.app.Activity
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.xtendroid.app.AndroidActivityProcessor.doTransform(AndroidActivityProcessor.java:75)
        at org.eclipse.xtend.lib.macro.AbstractClassProcessor.doTransform(AbstractClassProcessor.java:42)
        at org.eclipse.xtend.core.macro.AnnotationProcessor$2.run(AnnotationProcessor.java:150)
        at org.eclipse.xtend.core.macro.AnnotationProcessor.runWithCancelIndiciator(AnnotationProcessor.java:261)
        at org.eclipse.xtend.core.macro.AnnotationProcessor.inferencePhase(AnnotationProcessor.java:153)
        at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer.infer(XtendJvmModelInferrer.java:181)
        at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:350)
        at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:159)
        at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:133)
        at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:281)
        at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:271)
        at org.eclipse.xtend.core.compiler.batch.XtendBatchCompiler.compile(XtendBatchCompiler.java:392)
        at org.xtend.compiler.batch.FixedXtendBatchCompiler.compile(FixedXtendBatchCompiler.java:28)
        at org.xtend.compiler.batch.Main.compile(Main.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.xtend.gradle.tasks.XtendCompile.compile(XtendCompile.java:122)
        at org.xtend.gradle.tasks.XtendCompile.compile(XtendCompile.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
